### ISSUE TITLE
Wide band DOA estimation

### ISSUE THREAD

**Issue by unive3sal** [morriswmz/doa-tools#1]
I have some problems about ISSM MUSIC

**Comment by morriswmz** [comment]
Unfortunately wideband DOA estimation is not supported. My previous research was focused on performance analysis of narrowband DOA estimation algorithm. Therefore, this library was designed for narrowband models. You can see that many algorithms takes only a single `wavelength` parameter (not `wavelengths`). It is non-trivial to rewrite the current functions to support wideband models. Nevertheless, you can always extend the existing algorithms to wideband models. Feel free to fork this repository and modify the code as you like. It is released under the MIT license.
