### ISSUE TITLE
Question about coprime_1d

### ISSUE THREAD

**Issue by YetiXie1994** [morriswmz/doa-tools#2]
In array/corime_1d,  for the '2m' case, why you remove 'union'?

**Comment by morriswmz** [comment]
I originally used `union` to remove duplicated elements. Actually for co-prime pairs, there shouldn't be any overlapping elements for the `2M` configuration formula so I just removed the `union` call and used a simple concatenation instead.

If you are generating arrays whose subarray elements may have overlapping positions, and you do not want multiple sensors at the same position, `union` is required when combining subarray element positions.
